version: '3.8'

services:
  app:
    build: .
    container_name: digital-wallet-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/digital_wallet
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:14
    container_name: digital-wallet-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: digital_wallet
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
