services:
  app:
    build: .
    container_name: digital-wallet-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/digital_wallet_db
      NODE_ENV: production
      NEXTAUTH_SECRET: digital-wallet-super-secret-key-for-production-2025
      NEXTAUTH_URL: http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: digital-wallet-db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d digital_wallet_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: digital_wallet_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
